language: r
sudo: false

env:
  - BNET_FORCE_AUTOENCODER_TESTS=1
  - BNET_FORCE_UMAP_TESTS=1

# for pcaL1:
addons:
  apt:
    packages:
      - coinor-libclp-dev

r:
  - oldrel
  - release
  - devel

cache:
  packages: true
  directories:
    - $HOME/.keras
    - $HOME/.cache/pip

# r_check_args:
#   "--run-donttest --run-dontrun --timings"

before_install:
  # Keras and TensorFlow stuff
  - pip2 install --upgrade --ignore-installed --user travis pip setuptools wheel virtualenv
  - pip2 install --upgrade --ignore-installed --user keras h5py pyyaml requests Pillow scipy
  - pip2 install --upgrade --ignore-installed --user umap-learn
  # Install R packages
  - Rscript -e "update.packages(ask = FALSE)"
  - Rscript -e "if (!'covr' %in% rownames(installed.packages())) install.packages('covr')"
  - Rscript -e "if (!'rgl' %in% rownames(installed.packages())) install.packages('rgl')"
  - Rscript -e "if (!'roxygen2' %in% rownames(installed.packages())) install.packages('roxygen2')"
  # - Rscript -e "if (!'tensorflow' %in% rownames(installed.packages())) install.packages('tensorflow')"
  # Set CXX1X for R-devel, as R-devel does not detect CXX1X support for gcc 4.6.3,
  - if [[ "$TRAVIS_R_VERSION_STRING" = 'devel' ]]; then mkdir ~/.R && echo 'CXX1X=g++ -std=c++0x -g -O2 -fPIC' > ~/.R/Makevars; fi

before_script:
  # - Rscript -e "devtools::document()"
  - Rscript -e "tensorflow::install_tensorflow()"
  - Rscript -e "keras::install_keras()"

# Only report coverage for the release version
after_success:
  - test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'covr::codecov()'
